[features]
seeds = false
skip-lint = false
[programs.localnet]
betting = "AdffT7aGQ2gnavJutMWpHWph8kXnir1kCZs99YPTue87"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yangyi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
